taxi_rides_ny:
  outputs:
    dev:
      dataset: zoomcamp
      fixed_retries: 1
      keyfile: /.google/credentials/google_credentials.json
      location: europe-west2
      method: service-account
      priority: interactive
      project: peaceful-tome-448411-p7
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev